/*
try {
    throw new Error();
    console.log('hello')
} catch(e) {
    console.log('caught')
}
*/
//str.match("jello");

try {
    Number(5).toPrecision(3)
    } catch(e) {
    console.log("There was an error", e)
    }
